# setup vars
environ:                "stage" # dev || stage || prod
debugging:              true
login_user_passphrase:  "{{ vault_login_user_passphrase }}"


hostname:               "dataverse-stage.mse.jhu.edu"

# SSL vars
ssl_certificate_file:       "{{ vault_ssl_certificate_file }}"
ssl_certificate_key_file:   "{{ vault_ssl_certificate_key_file }}"
ssl_certificate_chain_file: "{{ vault_ssl_certificate_chain_file }}"

# NOTE: test values. at present, stage does not get the mount.
# dataverse_mountpoint: "/mnt/dvn"
# dataverse_filesdir: "{{ dataverse_mountpoint }}/dv-content" # /usr/local/dvn/data
# preprod - sam.mse.jhu.edu:/exports/apps/dvn.snapshot      /mnt/dvn        nfs     rw,proto=tcp    0 0
stores_fstab:
- name:   "/mnt/dvn"
  src:    "sam.mse.jhu.edu:/exports/apps/dvn.snapshot"
  fstype: "nfs"
  opts:   "rw,proto=tcp"
  state:   "absent" # present | absent

# admin_users: "{{ vault_admin_users }}"

# DOI vars
dataverse_doi_baseurl:    "https://mds.test.datacite.org/"
dataverse_doi_authority:  "10.33562"
dataverse_doi_shoulder:   ""

# solr vars
full_reindex: true
