# setup vars
environ:                "stage" # dev || stage || prod
debugging:              false

# private vars
login_user_passphrase:  "{{ vault_login_user_passphrase }}"

dataverse_branding_path:      "/var/www/dataverse/branding"
# TODO: support serving files from branding path
dataverse_logos_path:         "{{ dataverse.glassfish.root }}/glassfish/domains/{{ dataverse.glassfish.domain }}/docroot/logos"
dataverse_custom_files_path:  "templates"
dataverse_custom_header:      "custom-header.html"
dataverse_custom_logo:        "libraries.logo.small.horizontal.white.cropped.png"

# apache vars
apache_hostname:        "archive-stage.data.jhu.edu:443"
apache_fqdn:            "dataverse-stage.mse.jhu.edu"

# SSL vars
ssl_certificate_file:           "star_mse.jhu.edu.crt"
ssl_certificate_key_file:       "star_mse.jhu.edu.key"
ssl_certificate_chain_file:     "star_mse.jhu.edu_interim.crt"
