# setup vars
environ:                "stage" # dev || stage || prod
debugging:              true
login_user_passphrase:  "{{ vault_login_user_passphrase }}"

# apache vars
apache_hostname:        "archive-stage.data.jhu.edu:443"
apache_fqdn:            "dataverse-stage.mse.jhu.edu"

# SSL vars
ssl_certificate_file:       "{{ vault_ssl_certificate_file }}"
ssl_certificate_key_file:   "{{ vault_ssl_certificate_key_file }}"
ssl_certificate_chain_file: "{{ vault_ssl_certificate_chain_file }}"
