---
# REM: maunally install before using with
# $ ansible-galaxy install -r requirements.yml

- src: https://github.com/dheles/ansible-role-login-user
  name: login-user

- src: https://github.com/dheles/ansible-role-secure-ssh
  name: secure-ssh

- src: https://github.com/dheles/testup-ansible-role
  name: testup

- src: https://github.com/IQSS/dataverse-ansible.git
  name: dataverse

- src: https://github.com/dheles/dataverse-upgrade-ansible-role.git
  name: dataverse-upgrade

- src: https://github.com/dheles/postgres-ansible-role.git
  name: postgres

- src: https://github.com/dheles/firewalld-ansible-role.git
  name: firewalld
