# setup vars
environ:                        "prod" # dev || stage || prod
login_user_passphrase:          "{{ vault_login_user_passphrase }}"
debugging:                      False
set_up_tests:                   False

# db vars
postgres_version_major:         9
postgres_version_minor:         3
