# setup vars
environ:                        "prod" # dev || stage || prod
login_user_passphrase:          "{{ vault_login_user_passphrase }}"
debugging:                      False
set_up_tests:                   False

# db vars
postgres_version_major:         9
postgres_version_minor:         3

# apache vars
apache_hostname:        "archive.data.jhu.edu"
apache_fqdn:            "dms-dv01.mse.jhu.edu"

# SSL vars
ssl_certificate_file:           "{{ vault_ssl_certificate_file }}"
ssl_certificate_key_file:       "{{ vault_ssl_certificate_key_file }}"

dataverse_mountpoint: "/mnt/dvn"
dataverse_filesdir: "{{ dataverse_mountpoint }}/dv-content"
# prod    - sam.mse.jhu.edu:/exports/apps/dvn       /mnt/dvn        nfs             rw,vers=3,proto=tcp     0 0
stores_fstab:
- name:   "/mnt/dvn"
  src:    "sam.mse.jhu.edu:/exports/apps/dvn"
  fstype: "nfs"
  opts:   "rw,vers=3,proto=tcp"
  state:  "unmounted" # TODO: unmounted | mounted
