# REM: if you are looking for passwords or other variables
# that vary from dev to stage to prod, check the other subfolders

# setup vars
project:        "dataverse"
version:        "0.5.0"
login_user:     "deploy"
login_group:    "{{ login_user }}"

# testing vars
set_up_tests:   true

status_message_header: "" #  "System Outage: 12/13/18"
status_message_text:   "" # "The JHU Data Archive will be unavailable on December 13th, 2018 from approximately 10am until 12pm EST for system maintenance. We apologize for any inconvenience."

dataverse:
  adminpass: "{{ vault_dataverse_adminpass }}"
  allow_signups: true
  api:
    blocked_endpoints: "{{ dataverse_api_blocked_endpoints }}"
    blocked_policy: "{{ dataverse_api_blocked_policy }}"
    location: "http://localhost:{{ dataverse_api_port }}/api"
  branch:
  copyright: ", Johns Hopkins University"
  db:
    name: dvndb
    host: localhost
    user: "{{ vault_dataverse_dbuser }}"
    pass: "{{ vault_dataverse_dbpass }}"
    port: 5432
  demo: false
  doi:
    authority: "10.7281"
    protocol: "doi"
    shoulder: "T1/"
    provider: EZID
  filesdir: "{{ dataverse_filesdir }}"
  glassfish:
    user: glassfish
    group: glassfish
    root: /usr/local/glassfish4
    domain: domain1
    logformat: ulf
    adminuser: "{{ vault_dataverse_glassfish_adminuser }}"
    adminpass: "{{ vault_dataverse_glassfish_adminpass }}"
    timeout: 180
  google_analytics_key: "{{ vault_dataverse_google_analytics_key | default('') }}"
  memheap: 2048
  service_email: "{{ vault_dataverse_service_email }}"
  service_name: "{{ dataverse_service_name }}" #archive.data.jhu.edu
  shibboleth:
    enabled: false
    repo: "http://download.opensuse.org/repositories/security:/shibboleth/CentOS_7/security:shibboleth.repo"
  smtp: "{{ vault_dataverse_smtp }}"
  solr:
    group: solr
    root: /usr/local/solr
    user: solr
    version: 7.3.0
  thumbnails: true
  version: 4.9.4
rserve:
  host: localhost
  user: "{{ vault_rserve_user }}"
  pass: "{{ vault_rserve_pass }}"
  port: 6311

dataverse_service_name: "{{ hostname }}"
dataverse_api_port: 8080
dataverse_api_blocked_endpoints: "admin,test"
dataverse_api_blocked_policy: "localhost-only"
dataverse_glassfish_uid: 1100
dataverse_glassfish_gid: 1100
dataverse_mountpoint: "/usr/local/dvn"
dataverse_filesdir: "{{ dataverse_mountpoint }}/data"
stores_fstab: []

# db vars
db_name:                "{{ dataverse.db.name }}"
db_user:                "{{ dataverse.db.user }}"
db_password:            "{{ dataverse.db.pass }}"
db_backup_file:         "dataverse_{{ environ }}_backup.sql"
copy_backup_file:       "dataverse_prod_backup.sql"
db_retain_backup:       true
postgres_version_major: 9
postgres_version_minor: 3
postgres_jdbc_version:  "42.2.4"
# postgres_jdbc_driver:   "postgresql-{{ postgres_jdbc_version }}.jar"
postgres_hba_entries:
- type:                 "local"
  database:             "all"
  user:                 "postgres"
  method:               "ident"
- type:                 "local"
  database:             "{{ db_name }}"
  user:                 "{{ db_user }}"
  method:               "md5"
- type:                 "host"
  database:             "{{ db_name }}"
  user:                 "{{ db_user }}"
  address:              "samenet"
  method:               "md5"

hostname:               "localhost"
# apache vars
apache_hostname:        "{{ hostname }}"
apache_fqdn:            "{{ hostname }}"
apache_config_template: "templates/ssl.conf.j2"
apache_config_file:     "/etc/httpd/conf.d/ssl.conf"
apache_log_path:        "/var/log/httpd"
apache_log_level:       "warn"
apache_proxy_timeout:   600

# SSL vars
ssl_certificate_path:           "/etc/pki/tls/certs"
ssl_certificate_key_path:       "/etc/pki/tls/private"
ssl_certificate_file:           "localhost.crt"
ssl_certificate_key_file:       "localhost.key"
ssl_certificate_chain_file:     false

# firewalld vars:
firewalld_services:
- service: ssh
- service: http
- service: https

# branding vars
dataverse_working_dir:        "/home/{{ ansible_user }}"
dataverse_resources_path:     "{{ dataverse.glassfish.root }}/glassfish/domains/{{ dataverse.glassfish.domain }}/applications/dataverse/resources"
dataverse_images_path:        "{{ dataverse_resources_path }}/images"
dataverse_custom_files_path:  "templates"
dataverse_custom_header:      "custom-header.html"
dataverse_custom_logo:        "libraries.logo.small.horizontal.white.cropped.png"

# upgrade vars
dvu_current_version:  "4.6"
dvu_target_version:   "{{ dataverse.version }}"
dvu_extra_metadata_dir: "{{ dataverse_custom_files_path }}"
dvu_extra_metadata:
- file:     "dataContext.tsv"
  local:    true
  index:    true
- file:     "jhuSoftware.tsv"
  local:    true
  index:    true
- file:     "astrophysics.tsv"
  url:      "https://raw.githubusercontent.com/IQSS/dataverse/v{{ dvu_target_version }}/scripts/api/data/metadatablocks"
  index:    false
- file:     "biomedical.tsv"
  url:      "https://raw.githubusercontent.com/IQSS/dataverse/v{{ dvu_target_version }}/scripts/api/data/metadatablocks"
  index:    false
- file:     "geospatial.tsv"
  url:      "https://raw.githubusercontent.com/IQSS/dataverse/v{{ dvu_target_version }}/scripts/api/data/metadatablocks"
  index:    false
- file:     "journals.tsv"
  url:      "https://raw.githubusercontent.com/IQSS/dataverse/v{{ dvu_target_version }}/scripts/api/data/metadatablocks"
  index:    false
- file:     "social_science.tsv"
  url:      "https://raw.githubusercontent.com/IQSS/dataverse/v{{ dvu_target_version }}/scripts/api/data/metadatablocks"
  index:    false
