# setup vars
environ:                "dev" # dev || stage || prod
debugging:              true

# private vars
login_user_passphrase:  "{{ vault_login_user_passphrase }}"

# apache vars
apache_hostname:        "dataverse-dev.test:443"
apache_fqdn:            "dataverse-dev.test"
