# setup vars
environ:                "dev" # dev || stage || prod
debugging:              true

# private vars
login_user_passphrase:  "{{ vault_login_user_passphrase }}"

hostname:               "dataverse-dev.test"

