# setup vars
environ:                "dev" # dev || stage || prod
debugging:              true

# private vars
login_user_passphrase:  "{{ vault_login_user_passphrase }}"

dataverse_branding_path:      "/var/www/dataverse/branding"
# TODO: support serving files from branding path
dataverse_logos_path:         "{{ dataverse.glassfish.root }}/glassfish/domains/{{ dataverse.glassfish.domain }}/docroot/logos"
dataverse_custom_files_path:  "templates"
dataverse_custom_header:      "custom-header.html"
dataverse_custom_logo:        "libraries.logo.small.horizontal.white.cropped.png"
