---
- name: use aliases for passwords in glassfish
  hosts: app
  become: true

  tasks:
  - name: alias passwords
    include_role:
      name: dataverse-upgrade
      tasks_from: alias_passwords
      apply:
        no_log: "{{ not debugging }}"
    vars:
      password_aliases:
      - option: "doi.password"
        value:  "{{ dataverse_doi_password }}"
      - option: "dataverse.rserve.password"
        value:  "{{ rserve.pass }}"
