---
- name: do preinstall tasks
  hosts: app
  become: true

  tasks:
  - name: Install development packages
    yum:
      pkg: "{{ item }}"
      state: latest
    with_items: [git, bash-completion, vim]

  # TODO: use firewalld role, if needed
  # - name: Punch firewall holes for common dataverse ports
  #   firewalld:
  #     state: enabled
  #     port: "{{ item }}"
  #     permanent: true
  #     zone: public
  #     immediate: true
  #   with_items: [80/tcp, 443/tcp, 8080/tcp, 8181/tcp, 8983/tcp]
