---
- hosts: app

  tasks:
  - name: add pgpass entry for database
    include_role:
      name: postgres
      tasks_from: pgpass
    vars:
      admin_user: "{{ login_user }}"
      admin_group: "{{ login_group }}"
      database: "{{ db_name }}"
      user: "{{ db_user }}"
      password: "{{ db_password }}"
      state: "present"

  - name: upgrade dataverse
    include_role:
      name: dataverse-upgrade

- name: brand dataverse
  import_playbook: branding.yml
  tags:
  - branding

- name: reconfig dataverse
  import_playbook: config_environment.yml

- name: alias passwords
  import_playbook: alias_passwords.yml

# NOTE: workaround for https://github.com/IQSS/dataverse/issues/5575
- name: reindex problematic datasets
  import_playbook: reindex_specified.yml
